version: "3"

services:
  kutt:
    build: .
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: ${PGHOST:-postgres}
      DB_NAME: ${PGDATABASE:-kutt}
      DB_USER: ${PGUSER:-user}
      DB_PASSWORD: ${PGPASSWORD:-pass}
      REDIS_HOST: ${REDIS_HOST:-redis}

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${PGUSER:-user}
      POSTGRES_PASSWORD: ${PGPASSWORD:-pass}
      POSTGRES_DB: ${PGDATABASE:-kutt}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
